[load]
model_path = "imagenet"
base_model = "ResNet50V2"

[save]
model_path = ".Models/resnet_imagenet.h5"

[training]
train_images_folder = "/home/users/ucadatalab_group/javierj/SHARED/baby-stress/training_data/train"
val_images_folder = "/home/users/ucadatalab_group/javierj/SHARED/baby-stress/training_data/validation"
labels_names = "inferred"
n_labels = 2
color_mode= "rgb"
image_size = [224, 224]
shuffle = true
batch_size = 32
learning_rate = 0.00001
optimizer_name = "Adam"
epochs = 10
metrics = ["F1","binary_accuracy", "precision", "recall"]
early_stopping_metric = "val_F1"
early_stopping_mode = "max"
early_stopping_patience = 5

[wandb]
hyperparam_search_config_path = "/home/users/ucadatalab_group/javierj/Baby-Stress/CNN_stress/hyperparam_search_config.json"
save_dir = "/home/users/ucadatalab_group/javierj/Baby-Stress/hyperparams_search_results/Resnet"
train_images_folder = "/home/users/ucadatalab_group/javierj/SHARED/baby-stress/training_data/train"
val_images_folder = "/home/users/ucadatalab_group/javierj/SHARED/baby-stress/training_data/validation"